name = "helm-events"
main = "src/index.js"
compatibility_date = "2024-09-01"
workers_dev = false

[triggers]
crons = ["0 6 * * 1"]

[[kv_namespaces]]
binding = "EVENTS_KV"
id = "b50fc998715d4975a7674bc4ed232ac6"

[[routes]]
pattern = "helmfit.com/api/*"
zone_name = "helmfit.com"
